# cert_install.yml - this is working fine, creates the certificate on ACI
---
- name: Install a X.509 certificate for authentication
  hosts: dmzapic8
  gather_facts: no

  tasks:

  - name: Ensure we have a certificate installed
    aci_aaa_user_certificate:
      host: 'dmzapic8'
      username: 'apic#fallback\\ansible'
      password: 'myVerySekr7tPassword'
      aaa_user: ansible
      certificate_name: ansible
      certificate: "{{ lookup('file', 'ansible.crt') }}"
      validate_certs: no
    delegate_to: localhost

# usage: ansible-playbook  cert_install.yaml  -i hosts -vvv
